package scalan.util

import scalan._
import scala.reflect.runtime.universe.{WeakTypeTag, weakTypeTag}
import scalan.meta.ScalanAst._

package impl {
// Abs -----------------------------------
trait ExceptionsDefs extends scalan.Scalan with Exceptions {
  self: Scalan =>

  // entityProxy: single proxy for each type family
  implicit def proxySThrowable(p: Rep[SThrowable]): SThrowable = {
    proxyOps[SThrowable](p)(scala.reflect.classTag[SThrowable])
  }

  implicit def unwrapValueOfSThrowable(w: Rep[SThrowable]): Rep[Throwable] = w.wrappedValue

  implicit lazy val throwableElement: Elem[Throwable] =
    element[SThrowable].asInstanceOf[WrapperElem[_, _]].baseElem.asInstanceOf[Elem[Throwable]]

  // familyElem
  class SThrowableElem[To <: SThrowable]
    extends WrapperElem[Throwable, To] {
    lazy val parent: Option[Elem[_]] = None
    lazy val typeArgs = TypeArgs()
    override lazy val tag = {
      weakTypeTag[SThrowable].asInstanceOf[WeakTypeTag[To]]
    }
    override def convert(x: Rep[Def[_]]) = {
      val conv = fun {x: Rep[SThrowable] => convertSThrowable(x) }
      tryConvert(element[SThrowable], this, x, conv)
    }

    def convertSThrowable(x: Rep[SThrowable]): Rep[To] = {
      x.elem match {
        case _: SThrowableElem[_] => x.asRep[To]
        case e => !!!(s"Expected $x to have SThrowableElem[_], but got $e", x)
      }
    }
    lazy val baseElem = {
      new BaseTypeElem[Throwable, SThrowable](this.asInstanceOf[Elem[SThrowable]])
    }
    lazy val eTo: Elem[_] = new SThrowableImplElem(isoSThrowableImpl)
    override def getDefaultRep: Rep[To] = ???
  }

  implicit def sThrowableElement: Elem[SThrowable] =
    elemCache.getOrElseUpdate(
      (classOf[SThrowableElem[SThrowable]], Nil),
      new SThrowableElem[SThrowable]).asInstanceOf[Elem[SThrowable]]

  implicit case object SThrowableCompanionElem extends CompanionElem[SThrowableCompanionCtor] {
    lazy val tag = weakTypeTag[SThrowableCompanionCtor]
    protected def getDefaultRep = SThrowable
  }

  abstract class SThrowableCompanionCtor extends CompanionDef[SThrowableCompanionCtor] with SThrowableCompanion {
    def selfType = SThrowableCompanionElem
    override def toString = "SThrowable"
  }
  implicit def proxySThrowableCompanionCtor(p: Rep[SThrowableCompanionCtor]): SThrowableCompanionCtor =
    proxyOps[SThrowableCompanionCtor](p)

  // default wrapper implementation
  abstract class SThrowableImpl(val wrappedValue: Rep[Throwable]) extends SThrowable with Def[SThrowableImpl] {
    lazy val selfType = element[SThrowableImpl]

    def getMessage: Rep[String] =
      methodCallEx[String](self,
        this.getClass.getMethod("getMessage"),
        List())

    def initCause(cause: Rep[SThrowable]): Rep[SThrowable] =
      methodCallEx[SThrowable](self,
        this.getClass.getMethod("initCause", classOf[AnyRef]),
        List(cause.asInstanceOf[AnyRef]))
  }
  case class SThrowableImplCtor(override val wrappedValue: Rep[Throwable]) extends SThrowableImpl(wrappedValue) {
  }
  trait SThrowableImplCompanion
  // elem for concrete class
  class SThrowableImplElem(val iso: Iso[SThrowableImplData, SThrowableImpl])
    extends SThrowableElem[SThrowableImpl]
    with ConcreteElem[SThrowableImplData, SThrowableImpl] {
    override lazy val parent: Option[Elem[_]] = Some(sThrowableElement)
    override lazy val typeArgs = TypeArgs()
    override lazy val eTo: Elem[_] = this
    override def convertSThrowable(x: Rep[SThrowable]) = // Converter is not generated by meta
!!!("Cannot convert from SThrowable to SThrowableImpl: missing fields List(wrappedValue)")
    override def getDefaultRep = SThrowableImpl(DefaultOfThrowable)
    override lazy val tag = {
      weakTypeTag[SThrowableImpl]
    }
  }

  // state representation type
  type SThrowableImplData = Throwable

  // 3) Iso for concrete class
  class SThrowableImplIso
    extends EntityIso[SThrowableImplData, SThrowableImpl] with Def[SThrowableImplIso] {
    override def from(p: Rep[SThrowableImpl]) =
      p.wrappedValue
    override def to(p: Rep[Throwable]) = {
      val wrappedValue = p
      SThrowableImpl(wrappedValue)
    }
    lazy val eFrom = element[Throwable]
    lazy val eTo = new SThrowableImplElem(self)
    lazy val selfType = new SThrowableImplIsoElem
    def productArity = 0
    def productElement(n: Int) = ???
  }
  case class SThrowableImplIsoElem() extends Elem[SThrowableImplIso] {
    def getDefaultRep = reifyObject(new SThrowableImplIso())
    lazy val tag = {
      weakTypeTag[SThrowableImplIso]
    }
    lazy val typeArgs = TypeArgs()
  }
  // 4) constructor and deconstructor
  class SThrowableImplCompanionCtor extends CompanionDef[SThrowableImplCompanionCtor] {
    def selfType = SThrowableImplCompanionElem
    override def toString = "SThrowableImplCompanion"

    @scalan.OverloadId("fromFields")
    def apply(wrappedValue: Rep[Throwable]): Rep[SThrowableImpl] =
      mkSThrowableImpl(wrappedValue)

    def unapply(p: Rep[SThrowable]) = unmkSThrowableImpl(p)
  }
  lazy val SThrowableImplRep: Rep[SThrowableImplCompanionCtor] = new SThrowableImplCompanionCtor
  lazy val SThrowableImpl: SThrowableImplCompanionCtor = proxySThrowableImplCompanion(SThrowableImplRep)
  implicit def proxySThrowableImplCompanion(p: Rep[SThrowableImplCompanionCtor]): SThrowableImplCompanionCtor = {
    proxyOps[SThrowableImplCompanionCtor](p)
  }

  implicit case object SThrowableImplCompanionElem extends CompanionElem[SThrowableImplCompanionCtor] {
    lazy val tag = weakTypeTag[SThrowableImplCompanionCtor]
    protected def getDefaultRep = SThrowableImplRep
  }

  implicit def proxySThrowableImpl(p: Rep[SThrowableImpl]): SThrowableImpl =
    proxyOps[SThrowableImpl](p)

  implicit class ExtendedSThrowableImpl(p: Rep[SThrowableImpl]) {
    def toData: Rep[SThrowableImplData] = {
      isoSThrowableImpl.from(p)
    }
  }

  // 5) implicit resolution of Iso
  implicit def isoSThrowableImpl: Iso[SThrowableImplData, SThrowableImpl] =
    reifyObject(new SThrowableImplIso())

  registerModule(ExceptionsModule)

  lazy val SThrowable: Rep[SThrowableCompanionCtor] = new SThrowableCompanionCtor {
    def apply(msg: Rep[String]): Rep[SThrowable] =
      newObjEx[SThrowable](msg)
  }

  object SThrowableImplMethods {
  }

  def mkSThrowableImpl
    (wrappedValue: Rep[Throwable]): Rep[SThrowableImpl] = {
    new SThrowableImplCtor(wrappedValue)
  }
  def unmkSThrowableImpl(p: Rep[SThrowable]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: SThrowableImplElem @unchecked =>
      Some((p.asRep[SThrowableImpl].wrappedValue))
    case _ =>
      None
  }

  object SThrowableMethods {
    object getMessage {
      def unapply(d: Def[_]): Option[Rep[SThrowable]] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem.isInstanceOf[SThrowableElem[_]] && method.getName == "getMessage" =>
          Some(receiver).asInstanceOf[Option[Rep[SThrowable]]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[SThrowable]] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }

    object initCause {
      def unapply(d: Def[_]): Option[(Rep[SThrowable], Rep[SThrowable])] = d match {
        case MethodCall(receiver, method, Seq(cause, _*), _) if receiver.elem.isInstanceOf[SThrowableElem[_]] && method.getName == "initCause" =>
          Some((receiver, cause)).asInstanceOf[Option[(Rep[SThrowable], Rep[SThrowable])]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[(Rep[SThrowable], Rep[SThrowable])] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }

  object SThrowableCompanionMethods {
    object apply {
      def unapply(d: Def[_]): Option[Rep[String]] = d match {
        case MethodCall(receiver, method, Seq(msg, _*), _) if receiver.elem == SThrowableCompanionElem && method.getName == "apply" =>
          Some(msg).asInstanceOf[Option[Rep[String]]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[String]] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }
}

object ExceptionsModule extends scalan.ModuleInfo {
  val dump = "H4sIAAAAAAAAALVVTYgURxSu6Z04O7Pjrq6RYBSi6wR/0JmNBAwsISzrKIHJ7rK9GFhFqempHctUd1Wqa9YeEQ85eEhuISchB8GjCOIthBCUgOSQWw7BY1gIiEE86CnBV1XdPb0/s6MH51BU1bz3vfe+773qO0/RO6FE+0MPMxxUfaJw1TX76VBV3C94q8PIKbL8bHUh9/Gf39x20NgS2k7Ds1SqDmb0Kmk10PZ6oKjqVnxjrdDRhoWrabjaZnCV2GOqgcYXu4K43YAH1E8RaoMRsm4A8+6XEgtB5LpUPhoMtNYRoIo48EiouAwVOmD9ax5njHiK8qBGfb+jcJORWoOGCux3eDzwJFHEnWE4DEn4NbqO8g00TDQkTc9Fc+7OiR7uxrwWJaYK0tK41n6BCFNn11doNE5nTuhUwKZAfcGlSkIUAO4SbyXHfIDhAo03LuMVXIMQ7ZqrJA3a4DnGJW1bFkxM7bKtgUYE9r7CbTILnvqqAHWEhC1ruo1JJHJCCOiZEyaVao+ZaspMVTNTcYmkukWw/nNe8qiL7C83hFCkIY4NgEgQSD1oVb4975176Y74jnaOTIlFwPigT+saLYDIRwvfh8/P3DrpoNISKtFwuhkqiT2V1TmmawQHAVcm3ZRBLNsg10Q/uUyUabABRvNN3uomWnvcFzgApJjXMgjFqEeVNtZ3Y7E8m5IMSipBEtM8cJ7W229Ute+0EKz78Nov1/7e99dOBw3pHoyEzMAOAewW5ZhOmMGMQTmOSoJD1JJVyuU+2TnxnF649Z1yUK6BctHa9pprXgYlpyKJytbDdur/9OR/j0eXlRML37eIJP7PhV8f/LP6Wd5BzlqeilCAW4eikuQUKrmLlyS/ortG35X08n66K0dmu0XQVMNDT/5t/TaJzpvKjPIJAa/VbAAx/snNnz4k83cdNLxkZvM0w23TdlqDUyT0ltAwXyHS3hdWMNO7TVuv0CLLuMOSwcySYFXc31dFQTRDU5HQw5aUP2IFmeUBqZyer7xwf//hjtZD//+eQuUr5h1sncWsY5+sPQoNweMTFx/fFDdybRmOedbLQWO8z5zhzerJ8znMgDHI+A7kNnkR7924sfvZ7Yu7zCAPN6nysahMvsEYJ1P3FscUZcgaN+vuhLhR7RV/a6Aaa6iXw4nFZn1sWT2xoZt7BPfONtTxLXIo16OZpODJrK56ObIuyKeDgholYf529fKeydJpVRZ63btedb1W115Cq5TqkUdEKtxBFTdtUO0oyuJaJJro0ylurA3Qe/3lj7NH/7i/at6PklYZ2j5Iv5M9SaN1/b3N4mVSVSivRX8FVHDYBioJAAA="
}
}

trait ExceptionsModule extends scalan.util.impl.ExceptionsDefs {self: Scalan =>}
