package scalan.monads

import scalan._
import scala.reflect.runtime.universe._
import scalan.collections.CollectionsDslExp
import scala.reflect.runtime.universe.{WeakTypeTag, weakTypeTag}
import scalan.meta.ScalanAst._

package impl {
// Abs -----------------------------------
trait FreeStatesAbs extends scalan.ScalanDsl with FreeStates {
  self: MonadsDsl =>

  // single proxy for each type family
  implicit def proxyStateF[S, A](p: Rep[StateF[S, A]]): StateF[S, A] = {
    proxyOps[StateF[S, A]](p)(scala.reflect.classTag[StateF[S, A]])
  }

  // familyElem
  class StateFElem[S, A, To <: StateF[S, A]](implicit _eS: Elem[S], _eA: Elem[A])
    extends EntityElem[To] {
    def eS = _eS
    def eA = _eA
    lazy val parent: Option[Elem[_]] = None
    lazy val typeArgs = scala.collection.immutable.ListMap[String, TypeDesc]("S" -> eS, "A" -> eA)
    override def isEntityType = true
    override lazy val tag = {
      implicit val tagS = eS.tag
      implicit val tagA = eA.tag
      weakTypeTag[StateF[S, A]].asInstanceOf[WeakTypeTag[To]]
    }
    override def convert(x: Rep[Def[_]]) = {
      implicit val eTo: Elem[To] = this
      val conv = fun {x: Rep[StateF[S, A]] => convertStateF(x) }
      tryConvert(element[StateF[S, A]], this, x, conv)
    }

    def convertStateF(x: Rep[StateF[S, A]]): Rep[To] = {
      x.selfType1 match {
        case _: StateFElem[_, _, _] => x.asRep[To]
        case e => !!!(s"Expected $x to have StateFElem[_, _, _], but got $e", x)
      }
    }

    override def getDefaultRep: Rep[To] = ???
  }

  implicit def stateFElement[S, A](implicit eS: Elem[S], eA: Elem[A]): Elem[StateF[S, A]] =
    cachedElem[StateFElem[S, A, StateF[S, A]]](eS, eA)

  implicit case object StateFCompanionElem extends CompanionElem[StateFCompanionAbs] {
    lazy val tag = weakTypeTag[StateFCompanionAbs]
    protected def getDefaultRep = StateF
  }

  abstract class StateFCompanionAbs extends CompanionDef[StateFCompanionAbs] with StateFCompanion {
    def selfType = StateFCompanionElem
    override def toString = "StateF"
  }
  def StateF: Rep[StateFCompanionAbs]
  implicit def proxyStateFCompanionAbs(p: Rep[StateFCompanionAbs]): StateFCompanionAbs =
    proxyOps[StateFCompanionAbs](p)

  abstract class AbsStateGet[S, A]
      (f: Rep[S => A])(implicit eS: Elem[S], eA: Elem[A])
    extends StateGet[S, A](f) with Def[StateGet[S, A]] {
    lazy val selfType = element[StateGet[S, A]]
  }
  // elem for concrete class
  class StateGetElem[S, A](val iso: Iso[StateGetData[S, A], StateGet[S, A]])(implicit override val eS: Elem[S], override val eA: Elem[A])
    extends StateFElem[S, A, StateGet[S, A]]
    with ConcreteElem[StateGetData[S, A], StateGet[S, A]] {
    override lazy val parent: Option[Elem[_]] = Some(stateFElement(element[S], element[A]))
    override lazy val typeArgs = scala.collection.immutable.ListMap[String, TypeDesc]("S" -> eS, "A" -> eA)

    override def convertStateF(x: Rep[StateF[S, A]]) = // Converter is not generated by meta
!!!("Cannot convert from StateF to StateGet: missing fields List(f)")
    override def getDefaultRep = StateGet(constFun[S, A](element[A].defaultRepValue))
    override lazy val tag = {
      implicit val tagS = eS.tag
      implicit val tagA = eA.tag
      weakTypeTag[StateGet[S, A]]
    }
  }

  // state representation type
  type StateGetData[S, A] = S => A

  // 3) Iso for concrete class
  class StateGetIso[S, A](implicit eS: Elem[S], eA: Elem[A])
    extends EntityIso[StateGetData[S, A], StateGet[S, A]] with Def[StateGetIso[S, A]] {
    override def from(p: Rep[StateGet[S, A]]) =
      p.f
    override def to(p: Rep[S => A]) = {
      val f = p
      StateGet(f)
    }
    lazy val eFrom = element[S => A]
    lazy val eTo = new StateGetElem[S, A](self)
    lazy val selfType = new StateGetIsoElem[S, A](eS, eA)
    def productArity = 2
    def productElement(n: Int) = (eS, eA).productElement(n)
  }
  case class StateGetIsoElem[S, A](eS: Elem[S], eA: Elem[A]) extends Elem[StateGetIso[S, A]] {
    def isEntityType = true
    def getDefaultRep = reifyObject(new StateGetIso[S, A]()(eS, eA))
    lazy val tag = {
      implicit val tagS = eS.tag
      implicit val tagA = eA.tag
      weakTypeTag[StateGetIso[S, A]]
    }
  }
  // 4) constructor and deconstructor
  class StateGetCompanionAbs extends CompanionDef[StateGetCompanionAbs] with StateGetCompanion {
    def selfType = StateGetCompanionElem
    override def toString = "StateGet"

    @scalan.OverloadId("fromFields")
    def apply[S, A](f: Rep[S => A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StateGet[S, A]] =
      mkStateGet(f)

    def unapply[S, A](p: Rep[StateF[S, A]]) = unmkStateGet(p)
  }
  lazy val StateGetRep: Rep[StateGetCompanionAbs] = new StateGetCompanionAbs
  lazy val StateGet: StateGetCompanionAbs = proxyStateGetCompanion(StateGetRep)
  implicit def proxyStateGetCompanion(p: Rep[StateGetCompanionAbs]): StateGetCompanionAbs = {
    proxyOps[StateGetCompanionAbs](p)
  }

  implicit case object StateGetCompanionElem extends CompanionElem[StateGetCompanionAbs] {
    lazy val tag = weakTypeTag[StateGetCompanionAbs]
    protected def getDefaultRep = StateGet
  }

  implicit def proxyStateGet[S, A](p: Rep[StateGet[S, A]]): StateGet[S, A] =
    proxyOps[StateGet[S, A]](p)

  implicit class ExtendedStateGet[S, A](p: Rep[StateGet[S, A]])(implicit eS: Elem[S], eA: Elem[A]) {
    def toData: Rep[StateGetData[S, A]] = isoStateGet(eS, eA).from(p)
  }

  // 5) implicit resolution of Iso
  implicit def isoStateGet[S, A](implicit eS: Elem[S], eA: Elem[A]): Iso[StateGetData[S, A], StateGet[S, A]] =
    reifyObject(new StateGetIso[S, A]()(eS, eA))

  // 6) smart constructor and deconstructor
  def mkStateGet[S, A](f: Rep[S => A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StateGet[S, A]]
  def unmkStateGet[S, A](p: Rep[StateF[S, A]]): Option[(Rep[S => A])]

  abstract class AbsStatePut[S, A]
      (s: Rep[S], a: Rep[A])(implicit eS: Elem[S], eA: Elem[A])
    extends StatePut[S, A](s, a) with Def[StatePut[S, A]] {
    lazy val selfType = element[StatePut[S, A]]
  }
  // elem for concrete class
  class StatePutElem[S, A](val iso: Iso[StatePutData[S, A], StatePut[S, A]])(implicit override val eS: Elem[S], override val eA: Elem[A])
    extends StateFElem[S, A, StatePut[S, A]]
    with ConcreteElem[StatePutData[S, A], StatePut[S, A]] {
    override lazy val parent: Option[Elem[_]] = Some(stateFElement(element[S], element[A]))
    override lazy val typeArgs = scala.collection.immutable.ListMap[String, TypeDesc]("S" -> eS, "A" -> eA)

    override def convertStateF(x: Rep[StateF[S, A]]) = // Converter is not generated by meta
!!!("Cannot convert from StateF to StatePut: missing fields List(s, a)")
    override def getDefaultRep = StatePut(element[S].defaultRepValue, element[A].defaultRepValue)
    override lazy val tag = {
      implicit val tagS = eS.tag
      implicit val tagA = eA.tag
      weakTypeTag[StatePut[S, A]]
    }
  }

  // state representation type
  type StatePutData[S, A] = (S, A)

  // 3) Iso for concrete class
  class StatePutIso[S, A](implicit eS: Elem[S], eA: Elem[A])
    extends EntityIso[StatePutData[S, A], StatePut[S, A]] with Def[StatePutIso[S, A]] {
    override def from(p: Rep[StatePut[S, A]]) =
      (p.s, p.a)
    override def to(p: Rep[(S, A)]) = {
      val Pair(s, a) = p
      StatePut(s, a)
    }
    lazy val eFrom = pairElement(element[S], element[A])
    lazy val eTo = new StatePutElem[S, A](self)
    lazy val selfType = new StatePutIsoElem[S, A](eS, eA)
    def productArity = 2
    def productElement(n: Int) = (eS, eA).productElement(n)
  }
  case class StatePutIsoElem[S, A](eS: Elem[S], eA: Elem[A]) extends Elem[StatePutIso[S, A]] {
    def isEntityType = true
    def getDefaultRep = reifyObject(new StatePutIso[S, A]()(eS, eA))
    lazy val tag = {
      implicit val tagS = eS.tag
      implicit val tagA = eA.tag
      weakTypeTag[StatePutIso[S, A]]
    }
  }
  // 4) constructor and deconstructor
  class StatePutCompanionAbs extends CompanionDef[StatePutCompanionAbs] with StatePutCompanion {
    def selfType = StatePutCompanionElem
    override def toString = "StatePut"
    @scalan.OverloadId("fromData")
    def apply[S, A](p: Rep[StatePutData[S, A]])(implicit eS: Elem[S], eA: Elem[A]): Rep[StatePut[S, A]] =
      isoStatePut(eS, eA).to(p)
    @scalan.OverloadId("fromFields")
    def apply[S, A](s: Rep[S], a: Rep[A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StatePut[S, A]] =
      mkStatePut(s, a)

    def unapply[S, A](p: Rep[StateF[S, A]]) = unmkStatePut(p)
  }
  lazy val StatePutRep: Rep[StatePutCompanionAbs] = new StatePutCompanionAbs
  lazy val StatePut: StatePutCompanionAbs = proxyStatePutCompanion(StatePutRep)
  implicit def proxyStatePutCompanion(p: Rep[StatePutCompanionAbs]): StatePutCompanionAbs = {
    proxyOps[StatePutCompanionAbs](p)
  }

  implicit case object StatePutCompanionElem extends CompanionElem[StatePutCompanionAbs] {
    lazy val tag = weakTypeTag[StatePutCompanionAbs]
    protected def getDefaultRep = StatePut
  }

  implicit def proxyStatePut[S, A](p: Rep[StatePut[S, A]]): StatePut[S, A] =
    proxyOps[StatePut[S, A]](p)

  implicit class ExtendedStatePut[S, A](p: Rep[StatePut[S, A]])(implicit eS: Elem[S], eA: Elem[A]) {
    def toData: Rep[StatePutData[S, A]] = isoStatePut(eS, eA).from(p)
  }

  // 5) implicit resolution of Iso
  implicit def isoStatePut[S, A](implicit eS: Elem[S], eA: Elem[A]): Iso[StatePutData[S, A], StatePut[S, A]] =
    reifyObject(new StatePutIso[S, A]()(eS, eA))

  // 6) smart constructor and deconstructor
  def mkStatePut[S, A](s: Rep[S], a: Rep[A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StatePut[S, A]]
  def unmkStatePut[S, A](p: Rep[StateF[S, A]]): Option[(Rep[S], Rep[A])]

  registerModule(FreeStates_Module)
}

// Std -----------------------------------
trait FreeStatesStd extends scalan.ScalanDslStd with FreeStatesDsl {
  self: MonadsDslStd =>
  lazy val StateF: Rep[StateFCompanionAbs] = new StateFCompanionAbs {
  }

  case class StdStateGet[S, A]
      (override val f: Rep[S => A])(implicit eS: Elem[S], eA: Elem[A])
    extends AbsStateGet[S, A](f) {
  }

  def mkStateGet[S, A]
    (f: Rep[S => A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StateGet[S, A]] =
    new StdStateGet[S, A](f)
  def unmkStateGet[S, A](p: Rep[StateF[S, A]]) = p match {
    case p: StateGet[S, A] @unchecked =>
      Some((p.f))
    case _ => None
  }

  case class StdStatePut[S, A]
      (override val s: Rep[S], override val a: Rep[A])(implicit eS: Elem[S], eA: Elem[A])
    extends AbsStatePut[S, A](s, a) {
  }

  def mkStatePut[S, A]
    (s: Rep[S], a: Rep[A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StatePut[S, A]] =
    new StdStatePut[S, A](s, a)
  def unmkStatePut[S, A](p: Rep[StateF[S, A]]) = p match {
    case p: StatePut[S, A] @unchecked =>
      Some((p.s, p.a))
    case _ => None
  }
}

// Exp -----------------------------------
trait FreeStatesExp extends scalan.ScalanDslExp with FreeStatesDsl {
  self: MonadsDslExp =>
  lazy val StateF: Rep[StateFCompanionAbs] = new StateFCompanionAbs {
  }

  case class ExpStateGet[S, A]
      (override val f: Rep[S => A])(implicit eS: Elem[S], eA: Elem[A])
    extends AbsStateGet[S, A](f)

  object StateGetMethods {
  }

  object StateGetCompanionMethods {
  }

  def mkStateGet[S, A]
    (f: Rep[S => A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StateGet[S, A]] =
    new ExpStateGet[S, A](f)
  def unmkStateGet[S, A](p: Rep[StateF[S, A]]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: StateGetElem[S, A] @unchecked =>
      Some((p.asRep[StateGet[S, A]].f))
    case _ =>
      None
  }

  case class ExpStatePut[S, A]
      (override val s: Rep[S], override val a: Rep[A])(implicit eS: Elem[S], eA: Elem[A])
    extends AbsStatePut[S, A](s, a)

  object StatePutMethods {
  }

  object StatePutCompanionMethods {
  }

  def mkStatePut[S, A]
    (s: Rep[S], a: Rep[A])(implicit eS: Elem[S], eA: Elem[A]): Rep[StatePut[S, A]] =
    new ExpStatePut[S, A](s, a)
  def unmkStatePut[S, A](p: Rep[StateF[S, A]]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: StatePutElem[S, A] @unchecked =>
      Some((p.asRep[StatePut[S, A]].s, p.asRep[StatePut[S, A]].a))
    case _ =>
      None
  }

  object StateFMethods {
  }

  object StateFCompanionMethods {
    object unit {
      def unapply(d: Def[_]): Option[Rep[A] forSome {type S; type A}] = d match {
        case MethodCall(receiver, method, Seq(a, _*), _) if receiver.elem == StateFCompanionElem && method.getName == "unit" =>
          Some(a).asInstanceOf[Option[Rep[A] forSome {type S; type A}]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[A] forSome {type S; type A}] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }

    object get {
      def unapply(d: Def[_]): Option[Unit forSome {type S}] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem == StateFCompanionElem && method.getName == "get" =>
          Some(()).asInstanceOf[Option[Unit forSome {type S}]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Unit forSome {type S}] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }

    object set {
      def unapply(d: Def[_]): Option[Rep[S] forSome {type S}] = d match {
        case MethodCall(receiver, method, Seq(s, _*), _) if receiver.elem == StateFCompanionElem && method.getName == "set" =>
          Some(s).asInstanceOf[Option[Rep[S] forSome {type S}]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[S] forSome {type S}] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }

    object run {
      def unapply(d: Def[_]): Option[(Rep[FreeState[S, A]], Rep[S]) forSome {type S; type A}] = d match {
        case MethodCall(receiver, method, Seq(t, s, _*), _) if receiver.elem == StateFCompanionElem && method.getName == "run" =>
          Some((t, s)).asInstanceOf[Option[(Rep[FreeState[S, A]], Rep[S]) forSome {type S; type A}]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[(Rep[FreeState[S, A]], Rep[S]) forSome {type S; type A}] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }
}

object FreeStates_Module extends scalan.ModuleInfo {
  val dump = "H4sIAAAAAAAAANVXS4gcRRiuntndea3ZjfEdkl2X8bWamWAOOSyyjLszIWH2wXYkMgZDTXfNpmN3VdtVs/R4iJBDDupJRFBQCChechHv4sGAiAhKEMGTB08xIjmYk+Jf1Y/pmZ0eXUwOzqHorv7rf3zf91fVXL2JJrmHHucGtjGtOETgiq6ea1yU9ToVluitMbNrk1XS+e7pL1jx0lvrGTTbQlPnMV/ldgsVgoe678bPujCbqICpQbhgHhfo0aaKUDWYbRNDWIxWLcfpCty2SbVpcbHURBNtZvZeRReR1kSzBqOGRwTRV2zMOeHhfJ7IjKz4vaDeextuPwatyiqqiSpOe9gSkD7EmA3st4ir9yijPUegfWFqG65MC2xKxHehhpOOa6sw2SbKWY7LPBFFzUGE88yMXicohgl0b/MC3sFViLpd1YVn0W3pzMXGK3ibrIOJNJ+AGjixO6d7Lgmdl7gwB+L5LkIIWHlWJVbpY1aJMatIzMo68SxsW69h+XHTY34PBT8ti5Dvgotn/sFF5IHUqVl+46zx0m295GTkYl+mklMJTYGjuRSFKHoA26+23ua3Tlw5nkHFFipavNbmwsOGSMoghKuEKWVC5RwjiL1tYHAhjUEVpQY2QzIpGMxxMQVPIZbTQJRtGZaQxnJuOqQnBfuccElkqvmuFtc7n1Kv0tIKtu3NGw8feezX+osZlBkMUQCXOjSDFzkVaEqHckkjdC7HGYE0vY+wfK2pVzkU/P6YG5NLjMoTN34zrx1FZzMxlmHof0cfuJjkP/5Quv7UcgblW0rtDRtvtwBOXreJs+GtMCpaKM92iBd8ye1gWz6NpDNnkg7u2iIEOYlOFtARaD61VV0ioVtSLaBFAJQCFa8zSsqNzfIf+tfvXJUi9dB08CXo3b+s43/+tK8jlH4B0U6EbRb6PYbicBqzLml0qXH95HsHZg6d+1nxOmUyB1tKXAebaNKD1laFHAyh3RONxSBXnTlk/8It6+UrbwpFmOYP7h0b7QvQq0tq3eEx3EXb2qeXL9//+0fnDqjWy7ct4WC3fHQPjRf1yV1sLDSo/ZmgIVaSQXJJtOT4YDyrhjmgdL9ad4KIgZVziTWJOI9okYSUkUAZokcJTEhZj+zHIIs0B7VxDnZTL1A+yli5iEV4KF2EgNoDW8377JvLn2fQ5Ck02YE246C+NutSM6IDzkdBfPF8NKcN0gHwYw87MfzqN4/6aA0KtzHSoDYMSEkbrPg/7Wu76EJDaGt8RP+mk7VrOR6zfFxSi2o8ckclu9n9v0kWMk5KNl0le5JRItWpkTBnYUO7YyJLoWaA5aHpEQyOYj4orn+03zWo5Hip730R9o5Kyt6xSgwbe8SUF0niwEU32OmPvbt85tRDZ15QZ820qYyCL/E5PPpavobdJXWJfHLMJRKMynXHhT8J8HDsy+e+f/2bTz5WB3AfSIGKDY8QhRQEvSfKn1Fs8rishZSy9PBgAWFcvP3B+uK3n/2izuaiPKLgRkDja3l/A/SH+r2wpmLBLTsBMHSEPLQSanhfDh/+DYoNAJYUDQAA"
}
}

