package scalan.monads

import scala.io.StdIn
import scala.reflect.runtime.universe._
import scalan._
import scalan.monads._
import scala.reflect.runtime.universe.{WeakTypeTag, weakTypeTag}
import scalan.meta.ScalanAst._

package impl {
// Abs -----------------------------------
trait InteractionsAbs extends scalan.ScalanDsl with Interactions {
  self: InteractionsDsl =>

  // single proxy for each type family
  implicit def proxyInteract[A](p: Rep[Interact[A]]): Interact[A] = {
    proxyOps[Interact[A]](p)(scala.reflect.classTag[Interact[A]])
  }

  // familyElem
  class InteractElem[A, To <: Interact[A]](implicit _eA: Elem[A])
    extends EntityElem[To] {
    def eA = _eA
    lazy val parent: Option[Elem[_]] = None
    lazy val tyArgSubst: Map[String, TypeDesc] = {
      Map("A" -> Left(eA))
    }
    override def isEntityType = true
    override lazy val tag = {
      implicit val tagA = eA.tag
      weakTypeTag[Interact[A]].asInstanceOf[WeakTypeTag[To]]
    }
    override def convert(x: Rep[Def[_]]) = {
      implicit val eTo: Elem[To] = this
      val conv = fun {x: Rep[Interact[A]] => convertInteract(x) }
      tryConvert(element[Interact[A]], this, x, conv)
    }

    def convertInteract(x: Rep[Interact[A]]): Rep[To] = {
      x.selfType1 match {
        case _: InteractElem[_, _] => x.asRep[To]
        case e => !!!(s"Expected $x to have InteractElem[_, _], but got $e", x)
      }
    }

    override def getDefaultRep: Rep[To] = ???
  }

  implicit def interactElement[A](implicit eA: Elem[A]): Elem[Interact[A]] =
    cachedElem[InteractElem[A, Interact[A]]](eA)

  implicit case object InteractCompanionElem extends CompanionElem[InteractCompanionAbs] {
    lazy val tag = weakTypeTag[InteractCompanionAbs]
    protected def getDefaultRep = Interact
  }

  abstract class InteractCompanionAbs extends CompanionDef[InteractCompanionAbs] with InteractCompanion {
    def selfType = InteractCompanionElem
    override def toString = "Interact"
  }
  def Interact: Rep[InteractCompanionAbs]
  implicit def proxyInteractCompanionAbs(p: Rep[InteractCompanionAbs]): InteractCompanionAbs =
    proxyOps[InteractCompanionAbs](p)

  abstract class AbsAsk
      (prompt: Rep[String])
    extends Ask(prompt) with Def[Ask] {
    lazy val selfType = element[Ask]
  }
  // elem for concrete class
  class AskElem(val iso: Iso[AskData, Ask])
    extends InteractElem[String, Ask]
    with ConcreteElem[AskData, Ask] {
    override lazy val parent: Option[Elem[_]] = Some(interactElement(StringElement))
    override lazy val tyArgSubst: Map[String, TypeDesc] = {
      Map()
    }

    override def convertInteract(x: Rep[Interact[String]]) = // Converter is not generated by meta
!!!("Cannot convert from Interact to Ask: missing fields List(prompt)")
    override def getDefaultRep = Ask("")
    override lazy val tag = {
      weakTypeTag[Ask]
    }
  }

  // state representation type
  type AskData = String

  // 3) Iso for concrete class
  class AskIso
    extends EntityIso[AskData, Ask] with Def[AskIso] {
    override def from(p: Rep[Ask]) =
      p.prompt
    override def to(p: Rep[String]) = {
      val prompt = p
      Ask(prompt)
    }
    lazy val eFrom = element[String]
    lazy val eTo = new AskElem(self)
    lazy val selfType = new AskIsoElem
    def productArity = 0
    def productElement(n: Int) = ???
  }
  case class AskIsoElem() extends Elem[AskIso] {
    def isEntityType = true
    def getDefaultRep = reifyObject(new AskIso())
    lazy val tag = {
      weakTypeTag[AskIso]
    }
  }
  // 4) constructor and deconstructor
  class AskCompanionAbs extends CompanionDef[AskCompanionAbs] with AskCompanion {
    def selfType = AskCompanionElem
    override def toString = "Ask"

    def apply(prompt: Rep[String]): Rep[Ask] =
      mkAsk(prompt)

    def unapply(p: Rep[Interact[String]]) = unmkAsk(p)
  }
  lazy val AskRep: Rep[AskCompanionAbs] = new AskCompanionAbs
  lazy val Ask: AskCompanionAbs = proxyAskCompanion(AskRep)
  implicit def proxyAskCompanion(p: Rep[AskCompanionAbs]): AskCompanionAbs = {
    proxyOps[AskCompanionAbs](p)
  }

  implicit case object AskCompanionElem extends CompanionElem[AskCompanionAbs] {
    lazy val tag = weakTypeTag[AskCompanionAbs]
    protected def getDefaultRep = Ask
  }

  implicit def proxyAsk(p: Rep[Ask]): Ask =
    proxyOps[Ask](p)

  implicit class ExtendedAsk(p: Rep[Ask]) {
    def toData: Rep[AskData] = isoAsk.from(p)
  }

  // 5) implicit resolution of Iso
  implicit def isoAsk: Iso[AskData, Ask] =
    reifyObject(new AskIso())

  // 6) smart constructor and deconstructor
  def mkAsk(prompt: Rep[String]): Rep[Ask]
  def unmkAsk(p: Rep[Interact[String]]): Option[(Rep[String])]

  abstract class AbsTell
      (msg: Rep[String])
    extends Tell(msg) with Def[Tell] {
    lazy val selfType = element[Tell]
  }
  // elem for concrete class
  class TellElem(val iso: Iso[TellData, Tell])
    extends InteractElem[Unit, Tell]
    with ConcreteElem[TellData, Tell] {
    override lazy val parent: Option[Elem[_]] = Some(interactElement(UnitElement))
    override lazy val tyArgSubst: Map[String, TypeDesc] = {
      Map()
    }

    override def convertInteract(x: Rep[Interact[Unit]]) = // Converter is not generated by meta
!!!("Cannot convert from Interact to Tell: missing fields List(msg)")
    override def getDefaultRep = Tell("")
    override lazy val tag = {
      weakTypeTag[Tell]
    }
  }

  // state representation type
  type TellData = String

  // 3) Iso for concrete class
  class TellIso
    extends EntityIso[TellData, Tell] with Def[TellIso] {
    override def from(p: Rep[Tell]) =
      p.msg
    override def to(p: Rep[String]) = {
      val msg = p
      Tell(msg)
    }
    lazy val eFrom = element[String]
    lazy val eTo = new TellElem(self)
    lazy val selfType = new TellIsoElem
    def productArity = 0
    def productElement(n: Int) = ???
  }
  case class TellIsoElem() extends Elem[TellIso] {
    def isEntityType = true
    def getDefaultRep = reifyObject(new TellIso())
    lazy val tag = {
      weakTypeTag[TellIso]
    }
  }
  // 4) constructor and deconstructor
  class TellCompanionAbs extends CompanionDef[TellCompanionAbs] with TellCompanion {
    def selfType = TellCompanionElem
    override def toString = "Tell"

    def apply(msg: Rep[String]): Rep[Tell] =
      mkTell(msg)

    def unapply(p: Rep[Interact[Unit]]) = unmkTell(p)
  }
  lazy val TellRep: Rep[TellCompanionAbs] = new TellCompanionAbs
  lazy val Tell: TellCompanionAbs = proxyTellCompanion(TellRep)
  implicit def proxyTellCompanion(p: Rep[TellCompanionAbs]): TellCompanionAbs = {
    proxyOps[TellCompanionAbs](p)
  }

  implicit case object TellCompanionElem extends CompanionElem[TellCompanionAbs] {
    lazy val tag = weakTypeTag[TellCompanionAbs]
    protected def getDefaultRep = Tell
  }

  implicit def proxyTell(p: Rep[Tell]): Tell =
    proxyOps[Tell](p)

  implicit class ExtendedTell(p: Rep[Tell]) {
    def toData: Rep[TellData] = isoTell.from(p)
  }

  // 5) implicit resolution of Iso
  implicit def isoTell: Iso[TellData, Tell] =
    reifyObject(new TellIso())

  // 6) smart constructor and deconstructor
  def mkTell(msg: Rep[String]): Rep[Tell]
  def unmkTell(p: Rep[Interact[Unit]]): Option[(Rep[String])]

  registerModule(Interactions_Module)
}

// Std -----------------------------------
trait InteractionsStd extends scalan.ScalanDslStd with InteractionsDsl {
  self: InteractionsDslStd =>
  lazy val Interact: Rep[InteractCompanionAbs] = new InteractCompanionAbs {
  }

  case class StdAsk
      (override val prompt: Rep[String])
    extends AbsAsk(prompt) {
  }

  def mkAsk
    (prompt: Rep[String]): Rep[Ask] =
    new StdAsk(prompt)
  def unmkAsk(p: Rep[Interact[String]]) = p match {
    case p: Ask @unchecked =>
      Some((p.prompt))
    case _ => None
  }

  case class StdTell
      (override val msg: Rep[String])
    extends AbsTell(msg) {
  }

  def mkTell
    (msg: Rep[String]): Rep[Tell] =
    new StdTell(msg)
  def unmkTell(p: Rep[Interact[Unit]]) = p match {
    case p: Tell @unchecked =>
      Some((p.msg))
    case _ => None
  }
}

// Exp -----------------------------------
trait InteractionsExp extends scalan.ScalanDslExp with InteractionsDsl {
  self: InteractionsDslExp =>
  lazy val Interact: Rep[InteractCompanionAbs] = new InteractCompanionAbs {
  }

  case class ExpAsk
      (override val prompt: Rep[String])
    extends AbsAsk(prompt)

  object AskMethods {
    object toOper {
      def unapply(d: Def[_]): Option[Rep[Ask]] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem.isInstanceOf[AskElem] && method.getName == "toOper" =>
          Some(receiver).asInstanceOf[Option[Rep[Ask]]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[Ask]] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }

  object AskCompanionMethods {
  }

  def mkAsk
    (prompt: Rep[String]): Rep[Ask] =
    new ExpAsk(prompt)
  def unmkAsk(p: Rep[Interact[String]]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: AskElem @unchecked =>
      Some((p.asRep[Ask].prompt))
    case _ =>
      None
  }

  case class ExpTell
      (override val msg: Rep[String])
    extends AbsTell(msg)

  object TellMethods {
    object toOper {
      def unapply(d: Def[_]): Option[Rep[Tell]] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem.isInstanceOf[TellElem] && method.getName == "toOper" =>
          Some(receiver).asInstanceOf[Option[Rep[Tell]]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[Tell]] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }

  object TellCompanionMethods {
  }

  def mkTell
    (msg: Rep[String]): Rep[Tell] =
    new ExpTell(msg)
  def unmkTell(p: Rep[Interact[Unit]]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: TellElem @unchecked =>
      Some((p.asRep[Tell].msg))
    case _ =>
      None
  }

  object InteractMethods {
    object toOper {
      def unapply(d: Def[_]): Option[Rep[Interact[A]] forSome {type A}] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem.isInstanceOf[InteractElem[_, _]] && method.getName == "toOper" =>
          Some(receiver).asInstanceOf[Option[Rep[Interact[A]] forSome {type A}]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[Interact[A]] forSome {type A}] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }

  object InteractCompanionMethods {
  }
}

object Interactions_Module extends scalan.ModuleInfo {
  val dump = "H4sIAAAAAAAAALVWPYwbRRR+/jv/kssfIJDgDmM4gsCOkFCQroiM46Agc3e6vSBkItB4d+xsMju77IxPNkXKFNAhWopISDRpUAoKUBqEhCioEEKiSkEVgqIUpCLKm9kfr81t7ijYYrQz8/b9fN/7nvb6HSgIH14UJmGENx0qSdPQ720hG0aXS1tO33GtMaNn6PDWV2/cqOe++S4Ly31YukjEGcH6UA5euhMvfjek1YMy4SYV0vWFhOd6OkLLdBmjprRd3rIdZyzJgNFWzxZyvQf5gWtNP4IrkOnBYdPlpk8lNTqMCEFFeF6iKiM73pf1frrpzWLwlqqilahixye2xPQxxuHAfpt6xpS7fOpIOBSmtumptNCmaDue68soRBHdXXStaJvnBA/gaO8S2SUtDDFqGdK3+Qi/rHrEvExGdANNlHkeExaUDXemnt7nelAR0kKAzjke0ycTDwCQgdd0Es0ZPs0Yn6bCp2FQ3ybM/pioyy3fnUwheDI5gImHLl7Zx0XkgXa51fjkgvn+faPqZNXHE5VKUVe4hI5WUrpBU4E4/rj9mbj31rVTWaj0oWKL9kBIn5gySXmIVpVw7kqdcwwg8UfIVj2NLR2ljTYLLVE2XccjHD2FUNaQJ2abtlTG6qwWspMCfVF6NDLNTLxMXO9qSr26bzqEsa3bT736wp/d97KQnQ9RRpcGNr4fOZVQOsclVWjE7p9Pc+/RLd92sJ136evff3v+7s2Ngo5w1KJDMmbyXcLGNGiuMN4stgqVrdclLM0MypPZWnxEXTHCa7f/sn44CReyMS9hGQdrBXRREL/9Wv3lxOkslPpaOGcZGfWRGtFl1Nn0Oy6XfSi5u9QPboq7hKm3PVujGBYeEpZEOodIS1hNlbhHFQ3rWk6ZCIBqoIgNl9PG2a3G38ZPn19XDe9DLbgJNP/APvXP74eGUmsBEfV87LSAv2UJORwWAR5qOb4X0JXAm+E69Ej9nv3BtU+lhjQzmR8Um4NLqMx1/d2zj0A3GlhfX736+N0vPzymhVYa2NIhXuPkf5BZpIr/UUagQZgNkCdne7WsIKC1trjcSUZdWTRHlNFm4aoaKTQkYlFZaj2GKnjphIT8eW7Lf1OjIyTMn467Q8fCsI4YHZhotTb0unaAqh/boYztV3ZeGc3ugmiJhNdgHoMcdsX+qOBxpp1wmALMQg0HL+1IFHOP8pIjUJ/Gs+SZ9DmI/fTEdu84u3P6ZhYKb0NhiCNC9KAwcMfcihoV/wkkncg3o7PMfKNiYxKfOHFj6mcVZqmlotKZZwANa1EJSlHIZZS6y4klQrR8qKdUZISKQbKu3P9i4+Wfb/yhB3tFaQ+HEY9/LpIDfZ7A5WQG+MeQSBzbRmlSJ/0QTyPsq8EJAAA="
}
}

