package scalan.monads

import scala.reflect.runtime.universe._
import scalan._
import scalan.monads._
import scala.reflect.runtime.universe.{WeakTypeTag, weakTypeTag}
import scalan.meta.ScalanAst._

package impl {
// Abs -----------------------------------
trait IOsAbs extends scalan.ScalanDsl with IOs {
  self: IOsDsl =>

  // single proxy for each type family
  implicit def proxyIO[A](p: Rep[IO[A]]): IO[A] = {
    proxyOps[IO[A]](p)(scala.reflect.classTag[IO[A]])
  }

  // familyElem
  class IOElem[A, To <: IO[A]](implicit _eA: Elem[A])
    extends EntityElem[To] {
    def eA = _eA
    lazy val parent: Option[Elem[_]] = None
    lazy val typeArgs = TypeArgs("A" -> eA)
    override def isEntityType = true
    override lazy val tag = {
      implicit val tagA = eA.tag
      weakTypeTag[IO[A]].asInstanceOf[WeakTypeTag[To]]
    }
    override def convert(x: Rep[Def[_]]) = {
      implicit val eTo: Elem[To] = this
      val conv = fun {x: Rep[IO[A]] => convertIO(x) }
      tryConvert(element[IO[A]], this, x, conv)
    }

    def convertIO(x: Rep[IO[A]]): Rep[To] = {
      x.selfType1 match {
        case _: IOElem[_, _] => x.asRep[To]
        case e => !!!(s"Expected $x to have IOElem[_, _], but got $e", x)
      }
    }

    override def getDefaultRep: Rep[To] = ???
  }

  implicit def iOElement[A](implicit eA: Elem[A]): Elem[IO[A]] =
    cachedElem[IOElem[A, IO[A]]](eA)

  implicit case object IOCompanionElem extends CompanionElem[IOCompanionAbs] {
    lazy val tag = weakTypeTag[IOCompanionAbs]
    protected def getDefaultRep = IO
  }

  abstract class IOCompanionAbs extends CompanionDef[IOCompanionAbs] with IOCompanion {
    def selfType = IOCompanionElem
    override def toString = "IO"
  }
  def IO: Rep[IOCompanionAbs]
  implicit def proxyIOCompanionAbs(p: Rep[IOCompanionAbs]): IOCompanionAbs =
    proxyOps[IOCompanionAbs](p)

  abstract class AbsReadFile
      (fileName: Rep[String])
    extends ReadFile(fileName) with Def[ReadFile] {
    lazy val selfType = element[ReadFile]
  }
  // elem for concrete class
  class ReadFileElem(val iso: Iso[ReadFileData, ReadFile])
    extends IOElem[List[String], ReadFile]
    with ConcreteElem[ReadFileData, ReadFile] {
    override lazy val parent: Option[Elem[_]] = Some(iOElement(listElement(StringElement)))
    override lazy val typeArgs = TypeArgs()

    override def convertIO(x: Rep[IO[List[String]]]) = // Converter is not generated by meta
!!!("Cannot convert from IO to ReadFile: missing fields List(fileName)")
    override def getDefaultRep = ReadFile("")
    override lazy val tag = {
      weakTypeTag[ReadFile]
    }
  }

  // state representation type
  type ReadFileData = String

  // 3) Iso for concrete class
  class ReadFileIso
    extends EntityIso[ReadFileData, ReadFile] with Def[ReadFileIso] {
    override def from(p: Rep[ReadFile]) =
      p.fileName
    override def to(p: Rep[String]) = {
      val fileName = p
      ReadFile(fileName)
    }
    lazy val eFrom = element[String]
    lazy val eTo = new ReadFileElem(self)
    lazy val selfType = new ReadFileIsoElem
    def productArity = 0
    def productElement(n: Int) = ???
  }
  case class ReadFileIsoElem() extends Elem[ReadFileIso] {
    def isEntityType = true
    def getDefaultRep = reifyObject(new ReadFileIso())
    lazy val tag = {
      weakTypeTag[ReadFileIso]
    }
    lazy val typeArgs = TypeArgs()
  }
  // 4) constructor and deconstructor
  class ReadFileCompanionAbs extends CompanionDef[ReadFileCompanionAbs] with ReadFileCompanion {
    def selfType = ReadFileCompanionElem
    override def toString = "ReadFile"

    @scalan.OverloadId("fromFields")
    def apply(fileName: Rep[String]): Rep[ReadFile] =
      mkReadFile(fileName)

    def unapply(p: Rep[IO[List[String]]]) = unmkReadFile(p)
  }
  lazy val ReadFileRep: Rep[ReadFileCompanionAbs] = new ReadFileCompanionAbs
  lazy val ReadFile: ReadFileCompanionAbs = proxyReadFileCompanion(ReadFileRep)
  implicit def proxyReadFileCompanion(p: Rep[ReadFileCompanionAbs]): ReadFileCompanionAbs = {
    proxyOps[ReadFileCompanionAbs](p)
  }

  implicit case object ReadFileCompanionElem extends CompanionElem[ReadFileCompanionAbs] {
    lazy val tag = weakTypeTag[ReadFileCompanionAbs]
    protected def getDefaultRep = ReadFile
  }

  implicit def proxyReadFile(p: Rep[ReadFile]): ReadFile =
    proxyOps[ReadFile](p)

  implicit class ExtendedReadFile(p: Rep[ReadFile]) {
    def toData: Rep[ReadFileData] = isoReadFile.from(p)
  }

  // 5) implicit resolution of Iso
  implicit def isoReadFile: Iso[ReadFileData, ReadFile] =
    reifyObject(new ReadFileIso())

  // 6) smart constructor and deconstructor
  def mkReadFile(fileName: Rep[String]): Rep[ReadFile]
  def unmkReadFile(p: Rep[IO[List[String]]]): Option[(Rep[String])]

  abstract class AbsWriteFile
      (fileName: Rep[String], lines: Rep[List[String]])
    extends WriteFile(fileName, lines) with Def[WriteFile] {
    lazy val selfType = element[WriteFile]
  }
  // elem for concrete class
  class WriteFileElem(val iso: Iso[WriteFileData, WriteFile])
    extends IOElem[Unit, WriteFile]
    with ConcreteElem[WriteFileData, WriteFile] {
    override lazy val parent: Option[Elem[_]] = Some(iOElement(UnitElement))
    override lazy val typeArgs = TypeArgs()

    override def convertIO(x: Rep[IO[Unit]]) = // Converter is not generated by meta
!!!("Cannot convert from IO to WriteFile: missing fields List(fileName, lines)")
    override def getDefaultRep = WriteFile("", element[List[String]].defaultRepValue)
    override lazy val tag = {
      weakTypeTag[WriteFile]
    }
  }

  // state representation type
  type WriteFileData = (String, List[String])

  // 3) Iso for concrete class
  class WriteFileIso
    extends EntityIso[WriteFileData, WriteFile] with Def[WriteFileIso] {
    override def from(p: Rep[WriteFile]) =
      (p.fileName, p.lines)
    override def to(p: Rep[(String, List[String])]) = {
      val Pair(fileName, lines) = p
      WriteFile(fileName, lines)
    }
    lazy val eFrom = pairElement(element[String], element[List[String]])
    lazy val eTo = new WriteFileElem(self)
    lazy val selfType = new WriteFileIsoElem
    def productArity = 0
    def productElement(n: Int) = ???
  }
  case class WriteFileIsoElem() extends Elem[WriteFileIso] {
    def isEntityType = true
    def getDefaultRep = reifyObject(new WriteFileIso())
    lazy val tag = {
      weakTypeTag[WriteFileIso]
    }
    lazy val typeArgs = TypeArgs()
  }
  // 4) constructor and deconstructor
  class WriteFileCompanionAbs extends CompanionDef[WriteFileCompanionAbs] with WriteFileCompanion {
    def selfType = WriteFileCompanionElem
    override def toString = "WriteFile"
    @scalan.OverloadId("fromData")
    def apply(p: Rep[WriteFileData]): Rep[WriteFile] =
      isoWriteFile.to(p)
    @scalan.OverloadId("fromFields")
    def apply(fileName: Rep[String], lines: Rep[List[String]]): Rep[WriteFile] =
      mkWriteFile(fileName, lines)

    def unapply(p: Rep[IO[Unit]]) = unmkWriteFile(p)
  }
  lazy val WriteFileRep: Rep[WriteFileCompanionAbs] = new WriteFileCompanionAbs
  lazy val WriteFile: WriteFileCompanionAbs = proxyWriteFileCompanion(WriteFileRep)
  implicit def proxyWriteFileCompanion(p: Rep[WriteFileCompanionAbs]): WriteFileCompanionAbs = {
    proxyOps[WriteFileCompanionAbs](p)
  }

  implicit case object WriteFileCompanionElem extends CompanionElem[WriteFileCompanionAbs] {
    lazy val tag = weakTypeTag[WriteFileCompanionAbs]
    protected def getDefaultRep = WriteFile
  }

  implicit def proxyWriteFile(p: Rep[WriteFile]): WriteFile =
    proxyOps[WriteFile](p)

  implicit class ExtendedWriteFile(p: Rep[WriteFile]) {
    def toData: Rep[WriteFileData] = isoWriteFile.from(p)
  }

  // 5) implicit resolution of Iso
  implicit def isoWriteFile: Iso[WriteFileData, WriteFile] =
    reifyObject(new WriteFileIso())

  // 6) smart constructor and deconstructor
  def mkWriteFile(fileName: Rep[String], lines: Rep[List[String]]): Rep[WriteFile]
  def unmkWriteFile(p: Rep[IO[Unit]]): Option[(Rep[String], Rep[List[String]])]

  registerModule(IOs_Module)
}

// Std -----------------------------------
trait IOsStd extends scalan.ScalanDslStd with IOsDsl {
  self: IOsDslStd =>
  lazy val IO: Rep[IOCompanionAbs] = new IOCompanionAbs {
  }

  case class StdReadFile
      (override val fileName: Rep[String])
    extends AbsReadFile(fileName) {
  }

  def mkReadFile
    (fileName: Rep[String]): Rep[ReadFile] =
    new StdReadFile(fileName)
  def unmkReadFile(p: Rep[IO[List[String]]]) = p match {
    case p: ReadFile @unchecked =>
      Some((p.fileName))
    case _ => None
  }

  case class StdWriteFile
      (override val fileName: Rep[String], override val lines: Rep[List[String]])
    extends AbsWriteFile(fileName, lines) {
  }

  def mkWriteFile
    (fileName: Rep[String], lines: Rep[List[String]]): Rep[WriteFile] =
    new StdWriteFile(fileName, lines)
  def unmkWriteFile(p: Rep[IO[Unit]]) = p match {
    case p: WriteFile @unchecked =>
      Some((p.fileName, p.lines))
    case _ => None
  }
}

// Exp -----------------------------------
trait IOsExp extends scalan.ScalanDslExp with IOsDsl {
  self: IOsDslExp =>
  lazy val IO: Rep[IOCompanionAbs] = new IOCompanionAbs {
  }

  case class ExpReadFile
      (override val fileName: Rep[String])
    extends AbsReadFile(fileName)

  object ReadFileMethods {
    object toOper {
      def unapply(d: Def[_]): Option[Rep[ReadFile]] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem.isInstanceOf[ReadFileElem] && method.getName == "toOper" =>
          Some(receiver).asInstanceOf[Option[Rep[ReadFile]]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[ReadFile]] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }

  object ReadFileCompanionMethods {
  }

  def mkReadFile
    (fileName: Rep[String]): Rep[ReadFile] =
    new ExpReadFile(fileName)
  def unmkReadFile(p: Rep[IO[List[String]]]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: ReadFileElem @unchecked =>
      Some((p.asRep[ReadFile].fileName))
    case _ =>
      None
  }

  case class ExpWriteFile
      (override val fileName: Rep[String], override val lines: Rep[List[String]])
    extends AbsWriteFile(fileName, lines)

  object WriteFileMethods {
    object toOper {
      def unapply(d: Def[_]): Option[Rep[WriteFile]] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem.isInstanceOf[WriteFileElem] && method.getName == "toOper" =>
          Some(receiver).asInstanceOf[Option[Rep[WriteFile]]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[WriteFile]] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }

  object WriteFileCompanionMethods {
  }

  def mkWriteFile
    (fileName: Rep[String], lines: Rep[List[String]]): Rep[WriteFile] =
    new ExpWriteFile(fileName, lines)
  def unmkWriteFile(p: Rep[IO[Unit]]) = p.elem.asInstanceOf[Elem[_]] match {
    case _: WriteFileElem @unchecked =>
      Some((p.asRep[WriteFile].fileName, p.asRep[WriteFile].lines))
    case _ =>
      None
  }

  object IOMethods {
    object toOper {
      def unapply(d: Def[_]): Option[Rep[IO[A]] forSome {type A}] = d match {
        case MethodCall(receiver, method, _, _) if receiver.elem.isInstanceOf[IOElem[_, _]] && method.getName == "toOper" =>
          Some(receiver).asInstanceOf[Option[Rep[IO[A]] forSome {type A}]]
        case _ => None
      }
      def unapply(exp: Exp[_]): Option[Rep[IO[A]] forSome {type A}] = exp match {
        case Def(d) => unapply(d)
        case _ => None
      }
    }
  }

  object IOCompanionMethods {
  }
}

object IOs_Module extends scalan.ModuleInfo {
  val dump = "H4sIAAAAAAAAALVWTYhbVRS+SSaTv7FOR60/UJzG1KlVk2KRCoOUcSYjU9IkzOs4Eoty895Neut99z3fuxkSFxVcdKGuRFwILgqKmyKIO4VSUEFEBN26dlUrpQu7Ujz3vt+keWNcmMXlvfvOPd853/nOyb16E2VdBz3u6phhXjWJwFVNPa+5oqLVuaBidNYyBoxskN7PT163im+/10yjxQ6av4DdDZd1UMF7qA/t8FkTRgMVMNeJKyzHFehIQyHUdIsxogtq8Ro1zYHAXUZqDeqK1Qaa61rG6A10CaUaaFG3uO4QQbR1hl2XuP5+nsiIaPheUO+jlh1h8JrMohbL4pyDqYDwAWPRs98mtjbiFh+ZAh3wQ2vZMiywKZGhDTlsmTZTMJkGylHTthwRoOYA4YJlBK9zHMMGWmpcxHu4Bqj9miYcyvvSmY3113GfNMFEms9BDi5hvXMjm/jOS64wxvCGNkIIqvKMCqwacVYNOatKzioacShm9E0sP7YdazhC3i+VQWhog4un/sVF4IHUuVF557z+yh2tZKbl4aEMJacCmgdHjyYoRJUHuP1++3339otXTqVRsYOK1F3rusLBuojLwKerhDm3hIo5ZBA7fahgOamCCmUNbCZkUtAt08YcPPlcLkChGNWpkMZyb8EvTwL3OWGTwDQ1tFNhvssJ+SotrWPG2jcefvro7/WX0yg9DlEAlxo0gxM4FSi91fIdy/VeAWbAfYj1WBKWTdoONUHve+TZb77euXWtmVVwSwbp4QETL2E2IJ7UfPAoEIVbLgs0HxkUhpNrbp9UQ9JXbvxhfHcCnU+HpfIzm00d4GLpuY++Okran6dRvqOaaZPhvtKJrMUGcfUOylt7xPH2c3uYyaepWsn5yfsVjFOfAeoFWk6cAzaRdVlV/ZUK0i95LdK0OKlstit/aj98cFV2gIMWvC/eYPibnvrr1wM9oZpDoHyPMtXUQUkzMFM8PuTy4DSii54/zTLJwfJt+uqVd4WiNDUcHx6t7kVo1lV17sg+7AZz7YvLlx+49clr96ney3epMLFdOfEfOi9olP+xs5AiIZopj0TvcikDpQe3CTY2gdb1OHR58gxwHxhOfC+lxrtsvO0OwcaxJ6D3djgVd5dHAcTMD4caUSizVnz62SyjnLh3H5wyD6aqJx7kilqPz0Do0q5DBZmF0UJoGRnE8pn3IceDzoD09iMcNlJrMVcJnE/kMXt6pa3WlLy8cavew/F0OHnAgkQPbTfuZzdPX0uj7BmU7cHccRso27UG3Ai0D7cRQYbihWAvNa590Dp2sBlqXf2WURRUIhPNKNAVCLSaEOgG0Rl2iCHvCMSEO4zXwyc/PL175qHdHTVFFgxl5H0Jp+D0G9dZbK+q+8Gxfe4HYFSpmzbc/+Dh5LfP//LWj599qsZfVAtQAdRcoHuCwC2ODTfMp5yQj+bPClDQpTsfN4//9OVv6o+tKKcODGIeXrXif2jj2poHYLg2xWiFPpJDKCYjXS79fwD7m/k45QoAAA=="
}
}

