package scalan

import scalan.compilation.GraphVizExport
import scalan.primitives._
import scalan.collections._
import scalan.arrays._
import scalan.seq.BaseSeq
import scalan.staged.{Transforming, BaseExp, Expressions, TransformingExp}
import scalan.util.{ExceptionsDslExp, ExceptionsDslSeq, ExceptionsDsl/*, Exceptions*/}

abstract class Scalan
  extends Base
  with Debugging
  with Elems
  with Containers
  with TypeWrappers
  with ViewsDsl
  with Entities
  with Proxy
  with Tuples
  with Loops
  with TypeSum
  with UnBinOps
  with LogicalOps
  with OrderingOps
  with NumericOps
  with StringOps
  with Equal
  with MathOps
  with Functions
  with IfThenElse
  with Blocks
  with Monoids
  with PatternMatching
  with Maps
  with Transforming
  with ArrayOps
  with ArrayBuffers
  with Exceptions
  with ArrayViews
  with Thunks
  with Effects
  with Metadata
  with ListOps
  with ListViews
  with ConvertersDsl
  with Effectful
  with Structs

trait ScalanDsl
extends Scalan
  with ExceptionsDsl
  with AbstractStringsDsl

abstract class ScalanSeq
  extends Scalan
  with BaseSeq
  with ElemsSeq
  with ContainersSeq
  with TypeWrappersSeq
  with ViewsDslSeq
  with ProxySeq
  with TuplesSeq
  with LoopsSeq
  with TypeSumSeq
  with UnBinOpsSeq
  with NumericOpsSeq
  with FunctionsSeq
  with IfThenElseSeq
  with BlocksSeq
  with PatternMatchingSeq
  with MapsSeq
  with MonoidsSeq
  with ArrayOpsSeq
  with ArrayBuffersSeq
  with ExceptionsSeq
  with ArrayViewsSeq
  with StringOpsSeq
  with ThunksSeq
  with EffectsSeq
  with MetadataSeq
  with ListOpsSeq
  with ListViewsSeq
  with ConvertersDslSeq
  with EffectfulSeq
  with StructsSeq

class ScalanDslSeq
extends ScalanSeq
  with ScalanDsl
  with ExceptionsDslSeq
  with AbstractStringsDslSeq

abstract class ScalanExp
  extends Scalan
  with BaseExp
  with ElemsExp
  with ContainersExp
  with TypeWrappersExp
  with ViewsDslExp
  with ProxyExp
  with TuplesExp
  with LoopsExp
  with TypeSumExp
  with NumericOpsExp
  with UnBinOpsExp
  with LogicalOpsExp
  with EqualExp
  with FunctionsExp
  with IfThenElseExp
  with BlocksExp
  with PatternMatchingExp
  with MapsExp
  with TransformingExp
  with ArrayOpsExp
  with ArrayBuffersExp
  with ExceptionsExp
  with ArrayViewsExp
  with StringOpsExp
  with ThunksExp
  with EffectsExp
  with MetadataExp
  with ListOpsExp
  with ListViewsExp
  with ConvertersDslExp
  with EffectfulExp
  with StructsExp
  with RewriteRulesExp
  with GraphVizExport

class ScalanDslExp
extends ScalanExp
  with ScalanDsl
  with Expressions
  with ExceptionsDslExp
  with AbstractStringsDslExp
