package scalan

import scalan.compilation.GraphVizExport
import scalan.primitives._
import scalan.collections._
import scalan.arrays._
import scalan.seq.BaseStd
import scalan.staged.{Transforming, BaseExp, Expressions, TransformingExp}
import scalan.util.{ExceptionsDslExp, ExceptionsDslStd, ExceptionsDsl/*, Exceptions*/}

abstract class Scalan
  extends Base
  with Debugging
  with Elems
  with Containers
  with TypeWrappers
  with ViewsDsl
  with Entities
  with Proxy
  with Tuples
  with Loops
  with TypeSum
  with UnBinOps
  with LogicalOps
  with OrderingOps
  with NumericOps
  with StringOps
  with Equal
  with UniversalOps
  with MathOps
  with Functions
  with IfThenElse
  with Blocks
  with Monoids
  with PatternMatching
  with MapOps
  with MapViews
  with Transforming
  with Analyzing
  with ArrayOps
  with ArrayBuffers
  with Exceptions
  with ArrayViews
  with Thunks
  with Effects
  with Metadata
  with ListOps
  with ListViews
  with ConvertersDsl
  with Effectful
  with StructsDsl

trait ScalanDsl
extends Scalan
  with ExceptionsDsl
  with AbstractStringsDsl

abstract class ScalanStd
  extends Scalan
  with BaseStd
  with ElemsStd
  with ContainersStd
  with TypeWrappersStd
  with ViewsDslStd
  with ProxyStd
  with TuplesStd
  with LoopsStd
  with TypeSumStd
  with UnBinOpsStd
  with NumericOpsStd
  with FunctionsStd
  with IfThenElseStd
  with BlocksStd
  with PatternMatchingStd
  with MapOpsStd
  with MapViewsStd
  with MonoidsStd
  with AnalyzingStd
  with ArrayOpsStd
  with ArrayBuffersStd
  with ExceptionsStd
  with ArrayViewsStd
  with StringOpsStd
  with ThunksStd
  with EffectsStd
  with MetadataStd
  with ListOpsStd
  with ListViewsStd
  with ConvertersDslStd
  with EffectfulStd
  with StructsDslStd

class ScalanDslStd
extends ScalanStd
  with ScalanDsl
  with ExceptionsDslStd
  with AbstractStringsDslStd

abstract class ScalanExp
  extends Scalan
  with BaseExp
  with ElemsExp
  with ContainersExp
  with TypeWrappersExp
  with ViewsDslExp
  with ProxyExp
  with TuplesExp
  with LoopsExp
  with TypeSumExp
  with NumericOpsExp
  with UnBinOpsExp
  with LogicalOpsExp
  with OrderingOpsExp
  with EqualExp
  with UniversalOpsExp
  with FunctionsExp
  with IfThenElseExp
  with BlocksExp
  with PatternMatchingExp
  with MapOpsExp
  with MapViewsExp
  with TransformingExp
  with AnalyzingExp
  with ArrayOpsExp
  with ArrayBuffersExp
  with ExceptionsExp
  with ArrayViewsExp
  with StringOpsExp
  with ThunksExp
  with EffectsExp
  with MetadataExp
  with ListOpsExp
  with ListViewsExp
  with ConvertersDslExp
  with EffectfulExp
  with RewriteRulesExp
  with GraphVizExport
  with StructsDslExp

class ScalanDslExp
extends ScalanExp
  with ScalanDsl
  with Expressions
  with ExceptionsDslExp
  with AbstractStringsDslExp
