#!/bin/bash

function run {
    cd $1
    . testRun
    cd ..
}

ignoreFiles=""

ignoreFiles+=" -I check"
ignoreFiles+=" -I log"

rm log
touch log
for test in $( ls $ignoreFiles ); do
    run $test &>> log
done

function grepLog {
    pattern=$1
    color=$2
    export GREP_COLORS="ms=1;$color"
    grep $pattern log &> tmp
    grep $pattern -n tmp
    rm tmp
}

red=31
green=32
blue=34

grepLog cxx $blue
grepLog passed $green
grepLog "failed!!!" $red
