#!/bin/bash

testName=intPtr

scalanCore=../../../../../..
src=$scalanCore/lms-backend/it-out/scalan/it/lms/Pointer/$testName

ll $src/$testName.cxx

inc1=$src
inc2="$scalanCore/runtime/cpp/src"
inc3="/usr/lib/jvm/java-7-oracle/include/"
inc4="/usr/lib/jvm/java-7-oracle/include/linux"
inc5="/usr/local/include"
optInc="-I$inc1 -I$inc2 -I$inc3 -I$inc4 -I$inc5"

rm a.out
g++ -std=c++0x $optInc main.cpp
